### ISSUE TITLE
Spelling error in misaka_adjectives.json

### ISSUE THREAD

**Issue by kitallis** [pathsny/node-irc-relay#10]
"vigilantly" is spelled as "vigilantaly" in https://github.com/pathsny/node-irc-relay/blob/master/misaka_adjectives.json#L2

**Comment by IwikiwI** [comment]
Are you sure about the proposed fix? http://tellspell.com/english/vigilantely/176714/

**Comment by kitallis** [comment]
Yes. http://tellspell.com/english/vigilantly/125328/

On 16 August 2011 21:44, IwikiwI <
reply@reply.github.com>wrote:

> Are you sure about the proposed fix?
> http://tellspell.com/english/vigilantely/176714/
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pathsny/node-irc-relay/issues/10#issuecomment-1817818

## 

4, 8, 15, 16, 23, 42
Akshay Gupta (kitallis)
